//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWalletPayoutConfig
    {
        public int ConfigId { get; set; }
        public string TimePeriod { get; set; }
        public Nullable<decimal> MinimumPayout { get; set; }
        public Nullable<int> PayoutChargesPercent { get; set; }
    }
}
