//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWalletWithdrawalFund
    {
        public int WithdrawalFundId { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string WithdrawalFundMethod { get; set; }
        public Nullable<decimal> AmountPayble { get; set; }
        public string WithdrawalFundDescription { get; set; }
        public Nullable<decimal> WithdrawalFundCharge { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPending { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
    }
}
