//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpRequest
    {
        public int HelpRequestId { get; set; }
        public string HelpRequestName { get; set; }
        public string HelpRequestDescription { get; set; }
        public byte[] HelpRequestImage { get; set; }
        public string HelpRequestPriority { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsCheckByAdmin { get; set; }
    }
}
