//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int Id { get; set; }
        public string Designation { get; set; }
        public string RewardName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Leftlimit { get; set; }
        public Nullable<decimal> Rightlimit { get; set; }
        public byte[] Rewardimage { get; set; }
        public Nullable<bool> Isactive { get; set; }
    }
}
