//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingVideo
    {
        public int TrainingVideoId { get; set; }
        public string TrainingVideoName { get; set; }
        public string TrainingVideoURL { get; set; }
        public string TrainingVideoDescription { get; set; }
    }
}
