//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeDataTbl
    {
        public int Tree_ID { get; set; }
        public string Tree_Name { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DownlineMemberId { get; set; }
        public int Parent_ID { get; set; }
        public string Seq_index { get; set; }
        public string Full_index { get; set; }
        public string UserPosition { get; set; }
    }
}
