//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGenealogyTableLeft
    {
        public int GenealogyTableLeftId { get; set; }
        public string NoOfPerson { get; set; }
        public string CommissionDescription { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public string UserPositionName { get; set; }
        public Nullable<bool> UserPositionLeft { get; set; }
        public Nullable<bool> UserPositionRight { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> SponsorId { get; set; }
        public string SponsorName { get; set; }
        public Nullable<int> DownlineMemberId { get; set; }
        public string DownlineMemberName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> TableLevel { get; set; }
        public Nullable<bool> DirectCommision { get; set; }
        public Nullable<bool> MatchingCommision { get; set; }
    }
}
